regressions2.ds <-data.frame( 
# ----------------------------- SUB EXP ------   
  FACTORS = c(
    paste( "", sep = ""),
    paste( "REL * INT ANALYSIS", sep = ""),
    paste( "REL * INT(RES)", sep = ""),  
    paste( "REL(RES) * INT", sep = ""),
    paste( "ASSOC * INT ANALYSIS", sep = ""),
    paste( "REL * ASSOC ANALYSIS", sep = ""),
    paste( "REL * ASSOC(RES)", sep = ""),
    paste( "REL(RES) * ASSOC", sep = ""),
    paste( "", sep = ""),
    paste( "", sep = ""),
    paste( "REL * INT ANALYSIS", sep = ""),
    paste( "REL * INT(RES)", sep = ""),  
    paste( "REL(RES) * INT", sep = ""),
    paste( "ASSOC * INT ANALYSIS", sep = ""),
    paste( "REL * ASSOC ANALYSIS", sep = ""),
    paste( "REL * ASSOC(RES)", sep = ""),
    paste( "REL(RES) * ASSOC", sep = ""),
    paste( "", sep = ""),
    paste( "", sep = ""),
    paste( "REL * INT ANALYSIS", sep = ""),
    paste( "REL * INT(RES)", sep = ""),  
    paste( "REL(RES) * INT", sep = ""),
    paste( "ASSOC * INT ANALYSIS", sep = ""),
    paste( "REL * ASSOC ANALYSIS", sep = ""),
    paste( "REL * ASSOC(RES)", sep = ""),
    paste( "REL(RES) * ASSOC", sep = ""),
    paste( "", sep = ""),
    paste( "", sep = ""),
    paste( "REL * INT ANALYSIS", sep = ""),
    paste( "REL * INT(RES)", sep = ""),  
    paste( "REL(RES) * INT", sep = ""),
    paste( "ASSOC * INT ANALYSIS", sep = ""),
    paste( "REL * ASSOC ANALYSIS", sep = ""),
    paste( "REL * ASSOC(RES)", sep = ""),
    paste( "REL(RES) * ASSOC", sep = "")
  ),
  
  
  SUBEXPT = c( 
    paste( "", sep = ""),
    paste( "SemRel", sep = ""),
    paste( "SemRel", sep = ""),
    paste( "SemRel", sep = ""),
    paste( "SemRel", sep = ""),
    paste( "SemRel", sep = ""),
    paste( "SemRel", sep = ""),
    paste( "SemRel", sep = ""),
    paste( "", sep = ""),
    paste( "", sep = ""),
    paste( "CatCoord", sep = ""),
    paste( "CatCoord", sep = ""),
    paste( "CatCoord", sep = ""),
    paste( "CatCoord", sep = ""),
    paste( "CatCoord", sep = ""),
    paste( "CatCoord", sep = ""),
    paste( "CatCoord", sep = ""),
    paste( "", sep = ""),
    paste( "", sep = ""),
    paste( "Property", sep = ""),
    paste( "Property", sep = ""),
    paste( "Property", sep = ""),
    paste( "Property", sep = ""),
    paste( "Property", sep = ""),
    paste( "Property", sep = ""),
    paste( "Property", sep = ""),
    paste( "", sep = ""),
    paste( "", sep = ""),
    paste( "ALL", sep = ""),
    paste( "ALL", sep = ""),
    paste( "ALL", sep = ""),
    paste( "ALL", sep = ""),
    paste( "ALL", sep = ""),
    paste( "ALL", sep = ""),    
    paste( "ALL", sep = "")
   ),

  RAND.EFF.STRUCTURE = c( 
    paste( "F1 Rand", sep = ""),
    f.1,
    f.1a, 
    f.1b, 
    f.2,
    f.3,
    f.3a,
    f.3b,
     paste( "", sep = ""),
    paste( "F1 Rand", sep = ""), 
    f.10, 
    f.10a,
    f.10b, 
    paste( "", sep = ""),
    paste( "", sep = ""),
    paste( "", sep = ""), 
    paste( "", sep = ""),
    paste( "", sep = ""),
    paste( "F1 Rand", sep = ""),
    f.100, 
    f.100a, 
    f.100b, 
    f.200, 
    f.300, 
    f.300a, 
    f.300b, 
    paste( "", sep = ""),
    paste( "F1 Rand", sep = ""),
   f.1000, 
    f.1000a, 
    f.1000b, 
    f.2000, 
    f.3000, 
    f.3000a, 
    f.3000b
  ),
  
  # ----------------------------- RAND EFF STRUCTURE F2 -----
  RAND.EFF.STRUCTURE = c( 
    paste( "F2 Rand", sep = ""),
    ff.1,
    ff.1a, 
    ff.1b, 
    ff.2,
    ff.3,
    ff.3a,
    ff.3b,
    paste( "", sep = ""),
    paste( "F2 Rand", sep = ""), 
    ff.10, 
    ff.10a,
    ff.10b, 
    paste( "", sep = ""),
    paste( "", sep = ""),
    paste( "", sep = ""), 
    paste( "", sep = ""),
    paste( "", sep = ""),
    paste( "F2 Rand", sep = ""),
    ff.100, 
    ff.100a, 
    ff.100b, 
    ff.200, 
    ff.300, 
    ff.300a, 
    ff.300b, 
    paste( "", sep = ""),
    paste( "F2 Rand", sep = ""),
    ff.1000, 
    ff.1000a, 
    ff.1000b, 
    ff.2000, 
    ff.3000, 
    ff.3000a, 
    ff.3000b
  ),
  
# ----------------------------- FIXED EFFECTS ESTIMATES REL F1 ------
  FIXED.PRED1.F1   = c( 
    paste( "F1 REL/ASSOC", sep = ""),
    round( s.m1.f1[[10]][[9]], digits = 3),
    round( s.m1a.f1[[10]][[9]], digits = 3),
    round( s.m1b.f1[[10]][[9]], digits = 3),
    round( s.m2.f1[[10]][[10]], digits = 3),
    round( s.m3.f1[[10]][[9]], digits = 3),
    round( s.m3a.f1[[10]][[9]], digits = 3),
    round( s.m3b.f1[[10]][[9]], digits = 3),
    paste( "", sep = ""),
    paste( "F1 REL/ASSOC", sep = ""),
    round( s.m10.f1[[10]][[9]], digits = 3),
    round( s.m10a.f1[[10]][[9]], digits = 3),
    round( s.m10b.f1[[10]][[9]], digits = 3),
    paste( "", sep = ""),
    paste( "", sep = ""),
    paste( "", sep = ""),
    paste( "", sep = ""),
    paste( "", sep = ""),
    paste( "F1 REL/ASSOC", sep = ""),
    round( s.m100.f1[[10]][[9]], digits = 3),
    round( s.m100a.f1[[10]][[9]], digits = 3),
    round( s.m100b.f1[[10]][[9]], digits = 3),
    round( s.m200.f1[[10]][[10]], digits = 3),
    round( s.m300.f1[[10]][[9]], digits = 3),
    round( s.m300a.f1[[10]][[9]], digits = 3),
    round( s.m300b.f1[[10]][[9]], digits = 3),
    paste( "", sep = ""),
    paste( "F1 REL/ASSOC", sep = ""),
    round( s.m1000.f1[[10]][[9]], digits = 3),
    round( s.m1000a.f1[[10]][[9]], digits = 3),
    round( s.m1000b.f1[[10]][[9]], digits = 3),
    round( s.m2000.f1[[10]][[10]], digits = 3),
    round( s.m3000.f1[[10]][[9]], digits = 3),
    round( s.m3000a.f1[[10]][[9]], digits = 3),
    round( s.m3000b.f1[[10]][[9]], digits = 3)
  ),

relf1.round.ps  = c( 
  paste( "F1 REL/ASSOC", sep = ""),
  paste( get_range( p.s.m1.f1.r), " (", get_stars(  p.s.m1.f1.r),")", sep = ""),
  paste( get_range( p.s.m1a.f1.r), " (", get_stars( p.s.m1a.f1.r),")", sep = ""),
  paste( get_range( p.s.m1b.f1.r), " (", get_stars( p.s.m1b.f1.r),")", sep = ""),
  paste( get_range( p.s.m2.f1.r), " (", get_stars(  p.s.m2.f1.r),")", sep = ""),
  paste( get_range( p.s.m3.f1.r), " (", get_stars(  p.s.m3.f1.r),")", sep = ""),
  paste( get_range( p.s.m3a.f1.r), " (", get_stars( p.s.m3a.f1.r),")", sep = ""),
  paste( get_range( p.s.m3b.f1.r), " (", get_stars( p.s.m3b.f1.r),")", sep = ""),
  paste( "", sep = ""),
  paste( "F1 REL/ASSOC", sep = ""),
  paste( get_range( p.s.m10.f1.r), " (", get_stars(  p.s.m10.f1.r),")", sep = ""),
  paste( get_range( p.s.m10a.f1.r), " (", get_stars( p.s.m10a.f1.r),")", sep = ""),
  paste( get_range( p.s.m10b.f1.r), " (", get_stars( p.s.m10b.f1.r),")", sep = ""),
  paste( "", sep = ""), 
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "F1 REL/ASSOC", sep = ""),
  paste( get_range( p.s.m100.f1.r), " (", get_stars(  p.s.m100.f1.r),")", sep = ""),
  paste( get_range( p.s.m100a.f1.r), " (", get_stars( p.s.m100a.f1.r),")", sep = ""),
  paste( get_range( p.s.m100b.f1.r), " (", get_stars( p.s.m100b.f1.r),")", sep = ""),
  paste( get_range( p.s.m200.f1.r), " (", get_stars(  p.s.m200.f1.r),")", sep = ""),
  paste( get_range( p.s.m300.f1.r), " (", get_stars(  p.s.m300.f1.r),")", sep = ""),
  paste( get_range( p.s.m300a.f1.r), " (", get_stars( p.s.m300a.f1.r),")", sep = ""),
  paste( get_range( p.s.m300b.f1.r), " (", get_stars( p.s.m300b.f1.r),")", sep = ""),
  paste( "", sep = ""),
  paste( "F1 REL/ASSOC", sep = ""),
  paste( get_range( p.s.m1000.f1.r), " (", get_stars(  p.s.m1000.f1.r),")", sep = ""),
  paste( get_range( p.s.m1000a.f1.r), " (", get_stars( p.s.m1000a.f1.r),")", sep = ""),
  paste( get_range( p.s.m1000b.f1.r), " (", get_stars( p.s.m1000b.f1.r),")", sep = ""),
  paste( get_range( p.s.m2000.f1.r), " (", get_stars(  p.s.m2000.f1.r),")", sep = ""),
  paste( get_range( p.s.m3000.f1.r), " (", get_stars(  p.s.m3000.f1.r),")", sep = ""),
  paste( get_range( p.s.m3000a.f1.r), " (", get_stars( p.s.m3000a.f1.r),")", sep = ""),
  paste( get_range( p.s.m3000b.f1.r), " (", get_stars( p.s.m3000b.f1.r),")", sep = "")
  ),
 
# ----------------------------- FIXED EFFECTS ESTIMATES INT F1 ------
FIXED.PRED2.F1   = c( 
  paste( "F1 INT", sep = ""),
  round( s.m1.f1[[10]][[10]], digits = 3),
  round( s.m1a.f1[[10]][[10]], digits = 3),
  round( s.m1b.f1[[10]][[10]], digits = 3),
  round( s.m2.f1[[10]][[9]], digits = 3),
  round( s.m3.f1[[10]][[10]], digits = 3),
  round( s.m3a.f1[[10]][[10]], digits = 3),
  round( s.m3b.f1[[10]][[10]], digits = 3),
  paste( "", sep = ""),
  paste( "F1 INT", sep = ""),
  round( s.m10.f1[[10]][[10]], digits = 3),
  round( s.m10a.f1[[10]][[10]], digits = 3),
  round( s.m10b.f1[[10]][[10]], digits = 3),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "F1 INT", sep = ""),
  round( s.m100.f1[[10]][[10]], digits = 3),
  round( s.m100a.f1[[10]][[10]], digits = 3),
  round( s.m100b.f1[[10]][[10]], digits = 3),
  round( s.m200.f1[[10]][[9]], digits = 3),
  round( s.m300.f1[[10]][[10]], digits = 3),
  round( s.m300a.f1[[10]][[10]], digits = 3),
  round( s.m300b.f1[[10]][[10]], digits = 3),
  paste( "", sep = ""),
  paste( "F1 INT", sep = ""),
  round( s.m1000.f1[[10]][[10]], digits = 3),
  round( s.m1000a.f1[[10]][[10]], digits = 3),
  round( s.m1000b.f1[[10]][[10]], digits = 3),
  round( s.m2000.f1[[10]][[9]], digits = 3),
  round( s.m3000.f1[[10]][[10]], digits = 3),
  round( s.m3000a.f1[[10]][[10]], digits = 3),
  round( s.m3000b.f1[[10]][[10]], digits = 3)
),

intf1.round.ps  = c( 
  paste( "F1 INT", sep = ""),
  paste( get_range( p.s.m1.f1.i), " (", get_stars(  p.s.m1.f1.i),")", sep = ""),
  paste( get_range( p.s.m1a.f1.i), " (", get_stars( p.s.m1a.f1.i),")", sep = ""),
  paste( get_range( p.s.m1b.f1.i), " (", get_stars( p.s.m1b.f1.i),")", sep = ""),
  paste( get_range( p.s.m2.f1.i), " (", get_stars(  p.s.m2.f1.i),")", sep = ""),
  paste( get_range( p.s.m3.f1.i), " (", get_stars(  p.s.m3.f1.i),")", sep = ""),
  paste( get_range( p.s.m3a.f1.i), " (", get_stars( p.s.m3a.f1.i),")", sep = ""),
  paste( get_range( p.s.m3b.f1.i), " (", get_stars( p.s.m3b.f1.i),")", sep = ""),
  paste( "", sep = ""),
  paste( "F1 INT", sep = ""),
  paste( get_range( p.s.m10.f1.i), " (", get_stars(  p.s.m10.f1.i),")", sep = ""),
  paste( get_range( p.s.m10a.f1.i), " (", get_stars( p.s.m10a.f1.i),")", sep = ""),
  paste( get_range( p.s.m10b.f1.i), " (", get_stars( p.s.m10b.f1.i),")", sep = ""),
  paste( "", sep = ""), 
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "F1 INT", sep = ""),
  paste( get_range( p.s.m100.f1.i), " (", get_stars(  p.s.m100.f1.i),")", sep = ""),
  paste( get_range( p.s.m100a.f1.i), " (", get_stars( p.s.m100a.f1.i),")", sep = ""),
  paste( get_range( p.s.m100b.f1.i), " (", get_stars( p.s.m100b.f1.i),")", sep = ""),
  paste( get_range( p.s.m200.f1.i), " (", get_stars(  p.s.m200.f1.i),")", sep = ""),
  paste( get_range( p.s.m300.f1.i), " (", get_stars(  p.s.m300.f1.i),")", sep = ""),
  paste( get_range( p.s.m300a.f1.i), " (", get_stars( p.s.m300a.f1.i),")", sep = ""),
  paste( get_range( p.s.m300b.f1.i), " (", get_stars( p.s.m300b.f1.i),")", sep = ""),
  paste( "", sep = ""),
  paste( "F1 INT", sep = ""),
  paste( get_range( p.s.m1000.f1.i), " (", get_stars(  p.s.m1000.f1.i),")", sep = ""),
  paste( get_range( p.s.m1000a.f1.i), " (", get_stars( p.s.m1000a.f1.i),")", sep = ""),
  paste( get_range( p.s.m1000b.f1.i), " (", get_stars( p.s.m1000b.f1.i),")", sep = ""),
  paste( get_range( p.s.m2000.f1.i), " (", get_stars(  p.s.m2000.f1.i),")", sep = ""),
  paste( get_range( p.s.m3000.f1.i), " (", get_stars(  p.s.m3000.f1.i),")", sep = ""),
  paste( get_range( p.s.m3000a.f1.i), " (", get_stars( p.s.m3000a.f1.i),")", sep = ""),
  paste( get_range( p.s.m3000b.f1.i), " (", get_stars( p.s.m3000b.f1.i),")", sep = "")
),   
FIXED.PRED1and2.F1   = c( 
  paste( "F1 REL/ASSOC & INT", sep = ""),
  round( s.m1.f1[[10]][[11]], digits = 3),
  round( s.m1a.f1[[10]][[11]], digits = 3),
  round( s.m1b.f1[[10]][[11]], digits = 3),
  round( s.m2.f1[[10]][[11]], digits = 3),
  round( s.m3.f1[[10]][[11]], digits = 3),
  round( s.m3a.f1[[10]][[11]], digits = 3),
  round( s.m3b.f1[[10]][[11]], digits = 3),
  paste( "", sep = ""),
  paste( "F1 REL/ASSOC & INT", sep = ""),
  round( s.m10.f1[[10]][[11]], digits = 3),
  round( s.m10a.f1[[10]][[11]], digits = 3),
  round( s.m10b.f1[[10]][[11]], digits = 3),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "F1 REL/ASSOC & INT", sep = ""),
  round( s.m100.f1[[10]][[11]], digits = 3),
  round( s.m100a.f1[[10]][[11]], digits = 3),
  round( s.m100b.f1[[10]][[11]], digits = 3),
  round( s.m200.f1[[10]][[11]], digits = 3),
  round( s.m300.f1[[10]][[11]], digits = 3),
  round( s.m300a.f1[[10]][[11]], digits = 3),
  round( s.m300b.f1[[10]][[11]], digits = 3),
  paste( "", sep = ""),
  paste( "F1 REL/ASSOC & INT", sep = ""),
  round( s.m1000.f1[[10]][[11]], digits = 3),
  round( s.m1000a.f1[[10]][[11]], digits = 3),
  round( s.m1000b.f1[[10]][[11]], digits = 3),
  round( s.m2000.f1[[10]][[11]], digits = 3),
  round( s.m3000.f1[[10]][[11]], digits = 3),
  round( s.m3000a.f1[[10]][[11]], digits = 3),
  round( s.m3000b.f1[[10]][[11]], digits = 3)
),

relintf1.round.ps  = c( 
  paste( "F1 REL/ASSOC & INT", sep = ""),
  paste( get_range( p.s.m1.f1.ri), " (", get_stars(  p.s.m1.f1.ri),")", sep = ""),
  paste( get_range( p.s.m1a.f1.ri), " (", get_stars( p.s.m1a.f1.ri),")", sep = ""),
  paste( get_range( p.s.m1b.f1.ri), " (", get_stars( p.s.m1b.f1.ri),")", sep = ""),
  paste( get_range( p.s.m2.f1.ri), " (", get_stars(  p.s.m2.f1.ri),")", sep = ""),
  paste( get_range( p.s.m3.f1.ri), " (", get_stars(  p.s.m3.f1.ri),")", sep = ""),
  paste( get_range( p.s.m3a.f1.ri), " (", get_stars( p.s.m3a.f1.ri),")", sep = ""),
  paste( get_range( p.s.m3b.f1.ri), " (", get_stars( p.s.m3b.f1.ri),")", sep = ""),
  paste( "", sep = ""),
  paste( "F1 REL/ASSOC & INT", sep = ""),
  paste( get_range( p.s.m10.f1.ri), " (", get_stars(  p.s.m10.f1.ri),")", sep = ""),
  paste( get_range( p.s.m10a.f1.ri), " (", get_stars( p.s.m10a.f1.ri),")", sep = ""),
  paste( get_range( p.s.m10b.f1.ri), " (", get_stars( p.s.m10b.f1.ri),")", sep = ""),
  paste( "", sep = ""), 
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "F1 REL/ASSOC & INT", sep = ""),
  paste( get_range( p.s.m100.f1.ri), " (", get_stars(  p.s.m100.f1.ri),")", sep = ""),
  paste( get_range( p.s.m100a.f1.ri), " (", get_stars( p.s.m100a.f1.ri),")", sep = ""),
  paste( get_range( p.s.m100b.f1.ri), " (", get_stars( p.s.m100b.f1.ri),")", sep = ""),
  paste( get_range( p.s.m200.f1.ri), " (", get_stars(  p.s.m200.f1.ri),")", sep = ""),
  paste( get_range( p.s.m300.f1.ri), " (", get_stars(  p.s.m300.f1.ri),")", sep = ""),
  paste( get_range( p.s.m300a.f1.ri), " (", get_stars( p.s.m300a.f1.ri),")", sep = ""),
  paste( get_range( p.s.m300b.f1.ri), " (", get_stars( p.s.m300b.f1.ri),")", sep = ""),
  paste( "", sep = ""),
  paste( "F1 REL/ASSOC & INT", sep = ""),
  paste( get_range( p.s.m1000.f1.ri), " (", get_stars(  p.s.m1000.f1.ri),")", sep = ""),
  paste( get_range( p.s.m1000a.f1.ri), " (", get_stars( p.s.m1000a.f1.ri),")", sep = ""),
  paste( get_range( p.s.m1000b.f1.ri), " (", get_stars( p.s.m1000b.f1.ri),")", sep = ""),
  paste( get_range( p.s.m2000.f1.ri), " (", get_stars(  p.s.m2000.f1.ri),")", sep = ""),
  paste( get_range( p.s.m3000.f1.ri), " (", get_stars(  p.s.m3000.f1.ri),")", sep = ""),
  paste( get_range( p.s.m3000a.f1.ri), " (", get_stars( p.s.m3000a.f1.ri),")", sep = ""),
  paste( get_range( p.s.m3000b.f1.ri), " (", get_stars( p.s.m3000b.f1.ri),")", sep = "")
),   

FIXED.PRED1.F2   = c( 
  paste( "F2 REL/ASSOC", sep = ""),
  round( s.m1.f2[[10]][[9]], digits = 3),
  round( s.m1a.f2[[10]][[9]], digits = 3),
  round( s.m1b.f2[[10]][[9]], digits = 3),
  round( s.m2.f2[[10]][[10]], digits = 3),
  round( s.m3.f2[[10]][[9]], digits = 3),
  round( s.m3a.f2[[10]][[9]], digits = 3),
  round( s.m3b.f2[[10]][[9]], digits = 3),
  paste( "", sep = ""),
  paste( "F2 REL/ASSOC", sep = ""),
  round( s.m10.f2[[10]][[9]], digits = 3),
  round( s.m10a.f2[[10]][[9]], digits = 3),
  round( s.m10b.f2[[10]][[9]], digits = 3),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "F2 REL/ASSOC", sep = ""),
  round( s.m100.f2[[10]][[9]], digits = 3),
  round( s.m100a.f2[[10]][[9]], digits = 3),
  round( s.m100b.f2[[10]][[9]], digits = 3),
  round( s.m200.f2[[10]][[10]], digits = 3),
  round( s.m300.f2[[10]][[9]], digits = 3),
  round( s.m300a.f2[[10]][[9]], digits = 3),
  round( s.m300b.f2[[10]][[9]], digits = 3),
  paste( "", sep = ""),
  paste( "F2 REL/ASSOC", sep = ""),
  round( s.m1000.f2[[10]][[9]], digits = 3),
  round( s.m1000a.f2[[10]][[9]], digits = 3),
  round( s.m1000b.f2[[10]][[9]], digits = 3),
  round( s.m2000.f2[[10]][[10]], digits = 3),
  round( s.m3000.f2[[10]][[9]], digits = 3),
  round( s.m3000a.f2[[10]][[9]], digits = 3),
  round( s.m3000b.f2[[10]][[9]], digits = 3)
),

relf2.round.ps  = c( 
  paste( "F2 REL/ASSOC", sep = ""),
  paste( get_range( p.s.m1.f2.r), " (", get_stars(  p.s.m1.f2.r),")", sep = ""),
  paste( get_range( p.s.m1a.f2.r), " (", get_stars( p.s.m1a.f2.r),")", sep = ""),
  paste( get_range( p.s.m1b.f2.r), " (", get_stars( p.s.m1b.f2.r),")", sep = ""),
  paste( get_range( p.s.m2.f2.r), " (", get_stars(  p.s.m2.f2.r),")", sep = ""),
  paste( get_range( p.s.m3.f2.r), " (", get_stars(  p.s.m3.f2.r),")", sep = ""),
  paste( get_range( p.s.m3a.f2.r), " (", get_stars( p.s.m3a.f2.r),")", sep = ""),
  paste( get_range( p.s.m3b.f2.r), " (", get_stars( p.s.m3b.f2.r),")", sep = ""),
  paste( "", sep = ""),
  paste( "F2 REL/ASSOC", sep = ""),
  paste( get_range( p.s.m10.f2.r), " (", get_stars(  p.s.m10.f2.r),")", sep = ""),
  paste( get_range( p.s.m10a.f2.r), " (", get_stars( p.s.m10a.f2.r),")", sep = ""),
  paste( get_range( p.s.m10b.f2.r), " (", get_stars( p.s.m10b.f2.r),")", sep = ""),
  paste( "", sep = ""), 
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "F2 REL/ASSOC", sep = ""),
  paste( get_range( p.s.m100.f2.r), " (", get_stars(  p.s.m100.f2.r),")", sep = ""),
  paste( get_range( p.s.m100a.f2.r), " (", get_stars( p.s.m100a.f2.r),")", sep = ""),
  paste( get_range( p.s.m100b.f2.r), " (", get_stars( p.s.m100b.f2.r),")", sep = ""),
  paste( get_range( p.s.m200.f2.r), " (", get_stars(  p.s.m200.f2.r),")", sep = ""),
  paste( get_range( p.s.m300.f2.r), " (", get_stars(  p.s.m300.f2.r),")", sep = ""),
  paste( get_range( p.s.m300a.f2.r), " (", get_stars( p.s.m300a.f2.r),")", sep = ""),
  paste( get_range( p.s.m300b.f2.r), " (", get_stars( p.s.m300b.f2.r),")", sep = ""),
  paste( "", sep = ""),
  paste( "F2 REL/ASSOC", sep = ""),
  paste( get_range( p.s.m1000.f2.r), " (", get_stars(  p.s.m1000.f2.r),")", sep = ""),
  paste( get_range( p.s.m1000a.f2.r), " (", get_stars( p.s.m1000a.f2.r),")", sep = ""),
  paste( get_range( p.s.m1000b.f2.r), " (", get_stars( p.s.m1000b.f2.r),")", sep = ""),
  paste( get_range( p.s.m2000.f2.r), " (", get_stars(  p.s.m2000.f2.r),")", sep = ""),
  paste( get_range( p.s.m3000.f2.r), " (", get_stars(  p.s.m3000.f2.r),")", sep = ""),
  paste( get_range( p.s.m3000a.f2.r), " (", get_stars( p.s.m3000a.f2.r),")", sep = ""),
  paste( get_range( p.s.m3000b.f2.r), " (", get_stars( p.s.m3000b.f2.r),")", sep = "")
),

# ----------------------------- FIXED EFFECTS ESTIMATES INT F2 ------
FIXED.PRED2.F2   = c( 
  paste( "F2 INT", sep = ""),
  round( s.m1.f2[[10]][[10]], digits = 3),
  round( s.m1a.f2[[10]][[10]], digits = 3),
  round( s.m1b.f2[[10]][[10]], digits = 3),
  round( s.m2.f2[[10]][[9]], digits = 3),
  round( s.m3.f2[[10]][[10]], digits = 3),
  round( s.m3a.f2[[10]][[10]], digits = 3),
  round( s.m3b.f2[[10]][[10]], digits = 3),
  paste( "", sep = ""),
  paste( "F2 INT", sep = ""),
  round( s.m10.f2[[10]][[10]], digits = 3),
  round( s.m10a.f2[[10]][[10]], digits = 3),
  round( s.m10b.f2[[10]][[10]], digits = 3),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "F2 INT", sep = ""),
  round( s.m100.f2[[10]][[10]], digits = 3),
  round( s.m100a.f2[[10]][[10]], digits = 3),
  round( s.m100b.f2[[10]][[10]], digits = 3),
  round( s.m200.f2[[10]][[9]], digits = 3),
  round( s.m300.f2[[10]][[10]], digits = 3),
  round( s.m300a.f2[[10]][[10]], digits = 3),
  round( s.m300b.f2[[10]][[10]], digits = 3),
  paste( "", sep = ""),
  paste( "F2 INT", sep = ""),
  round( s.m1000.f2[[10]][[10]], digits = 3),
  round( s.m1000a.f2[[10]][[10]], digits = 3),
  round( s.m1000b.f2[[10]][[10]], digits = 3),
  round( s.m2000.f2[[10]][[9]], digits = 3),
  round( s.m3000.f2[[10]][[10]], digits = 3),
  round( s.m3000a.f2[[10]][[10]], digits = 3),
  round( s.m3000b.f2[[10]][[10]], digits = 3)
),

intf2.round.ps  = c( 
  paste( "F2 INT", sep = ""),
  paste( get_range( p.s.m1.f2.i), " (", get_stars(  p.s.m1.f2.i),")", sep = ""),
  paste( get_range( p.s.m1a.f2.i), " (", get_stars( p.s.m1a.f2.i),")", sep = ""),
  paste( get_range( p.s.m1b.f2.i), " (", get_stars( p.s.m1b.f2.i),")", sep = ""),
  paste( get_range( p.s.m2.f2.i), " (", get_stars(  p.s.m2.f2.i),")", sep = ""),
  paste( get_range( p.s.m3.f2.i), " (", get_stars(  p.s.m3.f2.i),")", sep = ""),
  paste( get_range( p.s.m3a.f2.i), " (", get_stars( p.s.m3a.f2.i),")", sep = ""),
  paste( get_range( p.s.m3b.f2.i), " (", get_stars( p.s.m3b.f2.i),")", sep = ""),
  paste( "", sep = ""),
  paste( "F2 INT", sep = ""),
  paste( get_range( p.s.m10.f2.i), " (", get_stars(  p.s.m10.f2.i),")", sep = ""),
  paste( get_range( p.s.m10a.f2.i), " (", get_stars( p.s.m10a.f2.i),")", sep = ""),
  paste( get_range( p.s.m10b.f2.i), " (", get_stars( p.s.m10b.f2.i),")", sep = ""),
  paste( "", sep = ""), 
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "F2 INT", sep = ""),
  paste( get_range( p.s.m100.f2.i), " (", get_stars(  p.s.m100.f2.i),")", sep = ""),
  paste( get_range( p.s.m100a.f2.i), " (", get_stars( p.s.m100a.f2.i),")", sep = ""),
  paste( get_range( p.s.m100b.f2.i), " (", get_stars( p.s.m100b.f2.i),")", sep = ""),
  paste( get_range( p.s.m200.f2.i), " (", get_stars(  p.s.m200.f2.i),")", sep = ""),
  paste( get_range( p.s.m300.f2.i), " (", get_stars(  p.s.m300.f2.i),")", sep = ""),
  paste( get_range( p.s.m300a.f2.i), " (", get_stars( p.s.m300a.f2.i),")", sep = ""),
  paste( get_range( p.s.m300b.f2.i), " (", get_stars( p.s.m300b.f2.i),")", sep = ""),
  paste( "", sep = ""),
  paste( "F2 INT", sep = ""),
  paste( get_range( p.s.m1000.f2.i), " (", get_stars(  p.s.m1000.f2.i),")", sep = ""),
  paste( get_range( p.s.m1000a.f2.i), " (", get_stars( p.s.m1000a.f2.i),")", sep = ""),
  paste( get_range( p.s.m1000b.f2.i), " (", get_stars( p.s.m1000b.f2.i),")", sep = ""),
  paste( get_range( p.s.m2000.f2.i), " (", get_stars(  p.s.m2000.f2.i),")", sep = ""),
  paste( get_range( p.s.m3000.f2.i), " (", get_stars(  p.s.m3000.f2.i),")", sep = ""),
  paste( get_range( p.s.m3000a.f2.i), " (", get_stars( p.s.m3000a.f2.i),")", sep = ""),
  paste( get_range( p.s.m3000b.f2.i), " (", get_stars( p.s.m3000b.f2.i),")", sep = "")
),   
FIXED.PRED1and2.F2   = c( 
  paste( "F2 REL/ASSOC & INT", sep = ""),
  round( s.m1.f2[[10]][[11]], digits = 3),
  round( s.m1a.f2[[10]][[11]], digits = 3),
  round( s.m1b.f2[[10]][[11]], digits = 3),
  round( s.m2.f2[[10]][[11]], digits = 3),
  round( s.m3.f2[[10]][[11]], digits = 3),
  round( s.m3a.f2[[10]][[11]], digits = 3),
  round( s.m3b.f2[[10]][[11]], digits = 3),
  paste( "", sep = ""),
  paste( "F2 REL/ASSOC & INT", sep = ""),
  round( s.m10.f2[[10]][[11]], digits = 3),
  round( s.m10a.f2[[10]][[11]], digits = 3),
  round( s.m10b.f2[[10]][[11]], digits = 3),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "F2 REL/ASSOC & INT", sep = ""),
  round( s.m100.f2[[10]][[11]], digits = 3),
  round( s.m100a.f2[[10]][[11]], digits = 3),
  round( s.m100b.f2[[10]][[11]], digits = 3),
  round( s.m200.f2[[10]][[11]], digits = 3),
  round( s.m300.f2[[10]][[11]], digits = 3),
  round( s.m300a.f2[[10]][[11]], digits = 3),
  round( s.m300b.f2[[10]][[11]], digits = 3),
  paste( "", sep = ""),
  paste( "F2 REL/ASSOC & INT", sep = ""),
  round( s.m1000.f2[[10]][[11]], digits = 3),
  round( s.m1000a.f2[[10]][[11]], digits = 3),
  round( s.m1000b.f2[[10]][[11]], digits = 3),
  round( s.m2000.f2[[10]][[11]], digits = 3),
  round( s.m3000.f2[[10]][[11]], digits = 3),
  round( s.m3000a.f2[[10]][[11]], digits = 3),
  round( s.m3000b.f2[[10]][[11]], digits = 3)
),

relintf2.round.ps  = c( 
  paste( "F2 REL/ASSOC & INT", sep = ""),
  paste( get_range( p.s.m1.f2.ri), " (", get_stars(  p.s.m1.f2.ri),")", sep = ""),
  paste( get_range( p.s.m1a.f2.ri), " (", get_stars( p.s.m1a.f2.ri),")", sep = ""),
  paste( get_range( p.s.m1b.f2.ri), " (", get_stars( p.s.m1b.f2.ri),")", sep = ""),
  paste( get_range( p.s.m2.f2.ri), " (", get_stars(  p.s.m2.f2.ri),")", sep = ""),
  paste( get_range( p.s.m3.f2.ri), " (", get_stars(  p.s.m3.f2.ri),")", sep = ""),
  paste( get_range( p.s.m3a.f2.ri), " (", get_stars( p.s.m3a.f2.ri),")", sep = ""),
  paste( get_range( p.s.m3b.f2.ri), " (", get_stars( p.s.m3b.f2.ri),")", sep = ""),
  paste( "", sep = ""),
  paste( "F2 REL/ASSOC & INT", sep = ""),
  paste( get_range( p.s.m10.f2.ri), " (", get_stars(  p.s.m10.f2.ri),")", sep = ""),
  paste( get_range( p.s.m10a.f2.ri), " (", get_stars( p.s.m10a.f2.ri),")", sep = ""),
  paste( get_range( p.s.m10b.f2.ri), " (", get_stars( p.s.m10b.f2.ri),")", sep = ""),
  paste( "", sep = ""), 
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "", sep = ""),
  paste( "F2 REL/ASSOC & INT", sep = ""),
  paste( get_range( p.s.m100.f2.ri), " (", get_stars(  p.s.m100.f2.ri),")", sep = ""),
  paste( get_range( p.s.m100a.f2.ri), " (", get_stars( p.s.m100a.f2.ri),")", sep = ""),
  paste( get_range( p.s.m100b.f2.ri), " (", get_stars( p.s.m100b.f2.ri),")", sep = ""),
  paste( get_range( p.s.m200.f2.ri), " (", get_stars(  p.s.m200.f2.ri),")", sep = ""),
  paste( get_range( p.s.m300.f2.ri), " (", get_stars(  p.s.m300.f2.ri),")", sep = ""),
  paste( get_range( p.s.m300a.f2.ri), " (", get_stars( p.s.m300a.f2.ri),")", sep = ""),
  paste( get_range( p.s.m300b.f2.ri), " (", get_stars( p.s.m300b.f2.ri),")", sep = ""),
  paste( "", sep = ""),
  paste( "F2 REL/ASSOC & INT", sep = ""),
  paste( get_range( p.s.m1000.f2.ri), " (", get_stars(  p.s.m1000.f2.ri),")", sep = ""),
  paste( get_range( p.s.m1000a.f2.ri), " (", get_stars( p.s.m1000a.f2.ri),")", sep = ""),
  paste( get_range( p.s.m1000b.f2.ri), " (", get_stars( p.s.m1000b.f2.ri),")", sep = ""),
  paste( get_range( p.s.m2000.f2.ri), " (", get_stars(  p.s.m2000.f2.ri),")", sep = ""),
  paste( get_range( p.s.m3000.f2.ri), " (", get_stars(  p.s.m3000.f2.ri),")", sep = ""),
  paste( get_range( p.s.m3000a.f2.ri), " (", get_stars( p.s.m3000a.f2.ri),")", sep = ""),
  paste( get_range( p.s.m3000b.f2.ri), " (", get_stars( p.s.m3000b.f2.ri),")", sep = "")
  ))