# ------------------------- ERRORS WITH DYSFLUENCIES ----------------
f2errout <- read.table("data/SR_F2_errordata.txt", header = T)
d <- f2errout 
d$item <- as.factor(d$item) 
d$pct <- ifelse(d$errd == 0 & d$errcord == 0, 0, (d$errd / (d$errcord)) * 100)

data.item <- aggregate(d$pct, list(d$item, d$integ, d$related, d$n2num ), mean)

colnames(data.item) <- c("item", "semint", "related", "n2num", "error") 
integ <- subset(data.item, semint   ==  "integ")
unint <- subset(data.item, semint   ==  "unint")
relat <- subset(data.item, related  ==  "rel")
unrel <- subset(data.item, related  ==  "unrel")
sing  <- subset(data.item, n2num    ==  "sing")
plur  <- subset(data.item, n2num    ==  "plur")
relat.int.plur   <- subset(data.item, related == "rel"   & semint  == "integ" & n2num == "plur")
relat.int.sing   <- subset(data.item, related == "rel"   & semint  == "integ" & n2num == "sing")
relat.unint.plur <- subset(data.item, related == "rel"   & semint  == "unint" & n2num == "plur")
relat.unint.sing <- subset(data.item, related == "rel"   & semint  == "unint" & n2num == "sing")
unrel.int.plur   <- subset(data.item, related == "unrel" & semint  == "integ" & n2num == "plur")
unrel.int.sing   <- subset(data.item, related == "unrel" & semint  == "integ" & n2num == "sing")
unrel.unint.plur <- subset(data.item, related == "unrel" & semint  == "unint" & n2num == "plur")
unrel.unint.sing <- subset(data.item, related == "unrel" & semint  == "unint" & n2num == "sing")
relat.plur       <- subset(data.item, related == "rel"   & n2num   == "plur")
relat.sing       <- subset(data.item, related == "rel"   & n2num   == "sing")
unrel.plur       <- subset(data.item, related == "unrel" & n2num   == "plur")
unrel.sing       <- subset(data.item, related == "unrel" & n2num   == "sing")
integ.plur       <- subset(data.item, semint  == "integ" & n2num   == "plur")
integ.sing       <- subset(data.item, semint  == "integ" & n2num   == "sing")
unint.plur       <- subset(data.item, semint  == "unint" & n2num   == "plur")
unint.sing       <- subset(data.item, semint  == "unint" & n2num   == "sing")
integ.relat      <- subset(data.item, semint  == "integ" & related == "rel")
integ.unrel      <- subset(data.item, semint  == "integ" & related == "unrel")
unint.relat      <- subset(data.item, semint  == "unint" & related == "rel")
unint.unrel      <- subset(data.item, semint  == "unint" & related == "unrel")
# ------------------------- ARCSINE TRANSFORMED ERRORS WITH DYSFLUENCIES ----------------

darc <- f2errout 
darc$item <- as.factor(darc$item) 
darc$pct <- ifelse(darc$errd == 0 & darc$errcord == 0, 0, (darc$errd / (darc$errcord)) * 100)
darc$arcs <- 2*asin(sqrt(darc$pct/100))
darc.data.item <- aggregate(darc$arcs, list(darc$item, darc$integ, darc$related, darc$n2num ), mean)
colnames(darc.data.item) <- c("item", "semint", "related", "n2num", "arcerr") 
arc.integ <- subset(darc.data.item, semint   ==  "integ")
arc.unint <- subset(darc.data.item, semint   ==  "unint")
arc.relat <- subset(darc.data.item, related  ==  "rel")
arc.unrel <- subset(darc.data.item, related  ==  "unrel")
arc.sing  <- subset(darc.data.item, n2num    ==  "sing")
arc.plur  <- subset(darc.data.item, n2num    ==  "plur")
arc.relat.int.plur   <- subset(darc.data.item, related == "rel"   & semint  == "integ" & n2num == "plur")
arc.relat.int.sing   <- subset(darc.data.item, related == "rel"   & semint  == "integ" & n2num == "sing")
arc.relat.unint.plur <- subset(darc.data.item, related == "rel"   & semint  == "unint" & n2num == "plur")
arc.relat.unint.sing <- subset(darc.data.item, related == "rel"   & semint  == "unint" & n2num == "sing")
arc.unrel.int.plur   <- subset(darc.data.item, related == "unrel" & semint  == "integ" & n2num == "plur")
arc.unrel.int.sing   <- subset(darc.data.item, related == "unrel" & semint  == "integ" & n2num == "sing")
arc.unrel.unint.plur <- subset(darc.data.item, related == "unrel" & semint  == "unint" & n2num == "plur")
arc.unrel.unint.sing <- subset(darc.data.item, related == "unrel" & semint  == "unint" & n2num == "sing")
arc.relat.plur       <- subset(darc.data.item, related == "rel"   & n2num   == "plur")
arc.relat.sing       <- subset(darc.data.item, related == "rel"   & n2num   == "sing")
arc.unrel.plur       <- subset(darc.data.item, related == "unrel" & n2num   == "plur")
arc.unrel.sing       <- subset(darc.data.item, related == "unrel" & n2num   == "sing")
arc.integ.plur       <- subset(darc.data.item, semint  == "integ" & n2num   == "plur")
arc.integ.sing       <- subset(darc.data.item, semint  == "integ" & n2num   == "sing")
arc.unint.plur       <- subset(darc.data.item, semint  == "unint" & n2num   == "plur")
arc.unint.sing       <- subset(darc.data.item, semint  == "unint" & n2num   == "sing")
arc.integ.relat      <- subset(darc.data.item, semint  == "integ" & related == "rel")
arc.integ.unrel      <- subset(darc.data.item, semint  == "integ" & related == "unrel")
arc.unint.relat      <- subset(darc.data.item, semint  == "unint" & related == "rel")
arc.unint.unrel      <- subset(darc.data.item, semint  == "unint" & related == "unrel")
# ------------------------- ERRORS WITH NO DYSFLUENCIES ----------------

nodys <- f2errout 
nodys$item <- as.factor(nodys$item) 
nodys$pct <- ifelse(nodys$errnod == 0 & nodys$errcornd == 0, 0, (nodys$errnd / (nodys$errcornd)) * 100)

nodys.data.item <- aggregate(nodys$pct, list(nodys$item, nodys$integ, nodys$related, nodys$n2num ), mean)
colnames(nodys.data.item) <- c("item", "semint", "related", "n2num", "nodys") 
nodys.integ <- subset(nodys.data.item, semint   ==  "integ")
nodys.unint <- subset(nodys.data.item, semint   ==  "unint")
nodys.relat <- subset(nodys.data.item, related  ==  "rel")
nodys.unrel <- subset(nodys.data.item, related  ==  "unrel")
nodys.sing  <- subset(nodys.data.item, n2num    ==  "sing")
nodys.plur  <- subset(nodys.data.item, n2num    ==  "plur")
nodys.relat.int.plur   <- subset(nodys.data.item, related == "rel"   & semint  == "integ" & n2num == "plur")
nodys.relat.int.sing   <- subset(nodys.data.item, related == "rel"   & semint  == "integ" & n2num == "sing")
nodys.relat.unint.plur <- subset(nodys.data.item, related == "rel"   & semint  == "unint" & n2num == "plur")
nodys.relat.unint.sing <- subset(nodys.data.item, related == "rel"   & semint  == "unint" & n2num == "sing")
nodys.unrel.int.plur   <- subset(nodys.data.item, related == "unrel" & semint  == "integ" & n2num == "plur")
nodys.unrel.int.sing   <- subset(nodys.data.item, related == "unrel" & semint  == "integ" & n2num == "sing")
nodys.unrel.unint.plur <- subset(nodys.data.item, related == "unrel" & semint  == "unint" & n2num == "plur")
nodys.unrel.unint.sing <- subset(nodys.data.item, related == "unrel" & semint  == "unint" & n2num == "sing")
nodys.relat.plur       <- subset(nodys.data.item, related == "rel"   & n2num   == "plur")
nodys.relat.sing       <- subset(nodys.data.item, related == "rel"   & n2num   == "sing")
nodys.unrel.plur       <- subset(nodys.data.item, related == "unrel" & n2num   == "plur")
nodys.unrel.sing       <- subset(nodys.data.item, related == "unrel" & n2num   == "sing")
nodys.integ.plur       <- subset(nodys.data.item, semint  == "integ" & n2num   == "plur")
nodys.integ.sing       <- subset(nodys.data.item, semint  == "integ" & n2num   == "sing")
nodys.unint.plur       <- subset(nodys.data.item, semint  == "unint" & n2num   == "plur")
nodys.unint.sing       <- subset(nodys.data.item, semint  == "unint" & n2num   == "sing")
nodys.integ.relat      <- subset(nodys.data.item, semint  == "integ" & related == "rel")
nodys.integ.unrel      <- subset(nodys.data.item, semint  == "integ" & related == "unrel")
nodys.unint.relat      <- subset(nodys.data.item, semint  == "unint" & related == "rel")
nodys.unint.unrel      <- subset(nodys.data.item, semint  == "unint" & related == "unrel")
# ------------------------  ERRORS COUNTS ----------------


cnt <- f2errout 
cnt$item <- as.factor(cnt$item) 
cnt.data.item <- aggregate(cnt$errd, list(cnt$item, cnt$integ, cnt$related, cnt$n2num ), sum)
colnames(cnt.data.item) <- c("item", "semint", "related", "n2num", "count") 
cnt.integ <- subset(cnt.data.item, semint   ==  "integ")
cnt.unint <- subset(cnt.data.item, semint   ==  "unint")
cnt.relat <- subset(cnt.data.item, related  ==  "rel")
cnt.unrel <- subset(cnt.data.item, related  ==  "unrel")
cnt.sing  <- subset(cnt.data.item, n2num    ==  "sing")
cnt.plur  <- subset(cnt.data.item, n2num    ==  "plur")
cnt.relat.int.plur   <- subset(cnt.data.item, related == "rel"   & semint  == "integ" & n2num == "plur")
cnt.relat.int.sing   <- subset(cnt.data.item, related == "rel"   & semint  == "integ" & n2num == "sing")
cnt.relat.unint.plur <- subset(cnt.data.item, related == "rel"   & semint  == "unint" & n2num == "plur")
cnt.relat.unint.sing <- subset(cnt.data.item, related == "rel"   & semint  == "unint" & n2num == "sing")
cnt.unrel.int.plur   <- subset(cnt.data.item, related == "unrel" & semint  == "integ" & n2num == "plur")
cnt.unrel.int.sing   <- subset(cnt.data.item, related == "unrel" & semint  == "integ" & n2num == "sing")
cnt.unrel.unint.plur <- subset(cnt.data.item, related == "unrel" & semint  == "unint" & n2num == "plur")
cnt.unrel.unint.sing <- subset(cnt.data.item, related == "unrel" & semint  == "unint" & n2num == "sing")
cnt.relat.plur       <- subset(cnt.data.item, related == "rel"   & n2num   == "plur")
cnt.relat.sing       <- subset(cnt.data.item, related == "rel"   & n2num   == "sing")
cnt.unrel.plur       <- subset(cnt.data.item, related == "unrel" & n2num   == "plur")
cnt.unrel.sing       <- subset(cnt.data.item, related == "unrel" & n2num   == "sing")
cnt.integ.plur       <- subset(cnt.data.item, semint  == "integ" & n2num   == "plur")
cnt.integ.sing       <- subset(cnt.data.item, semint  == "integ" & n2num   == "sing")
cnt.unint.plur       <- subset(cnt.data.item, semint  == "unint" & n2num   == "plur")
cnt.unint.sing       <- subset(cnt.data.item, semint  == "unint" & n2num   == "sing")
cnt.integ.relat      <- subset(cnt.data.item, semint  == "integ" & related == "rel")
cnt.integ.unrel      <- subset(cnt.data.item, semint  == "integ" & related == "unrel")
cnt.unint.relat      <- subset(cnt.data.item, semint  == "unint" & related == "rel")
cnt.unint.unrel      <- subset(cnt.data.item, semint  == "unint" & related == "unrel")

