# ------------------------- ERRORS WITH DYSFLUENCIES ----------------
f1errout <- read.table("data/SR_F1_errrel.txt", header = T)
d <- f1errout 
d$subj <- as.factor(d$subj) 
d$pct <- ifelse(d$errd == 0 & d$errcord == 0, 0, (d$errd / (d$errcord)) * 100)
data.subj <- aggregate(d$pct, list(d$subj, d$semint, d$related, d$n2num ), mean)
colnames(data.subj) <- c("subj", "semint", "related", "n2num", "error") 
integ <- subset(data.subj, semint   ==  "integ")
unint <- subset(data.subj, semint   ==  "unint")
relat <- subset(data.subj, related  ==  "rel")
unrel <- subset(data.subj, related  ==  "unrel")
sing  <- subset(data.subj, n2num    ==  "sing")
plur  <- subset(data.subj, n2num    ==  "plur")
relat.int.plur   <- subset(data.subj, related == "rel"   & semint  == "integ" & n2num == "plur")
relat.int.sing   <- subset(data.subj, related == "rel"   & semint  == "integ" & n2num == "sing")
relat.unint.plur <- subset(data.subj, related == "rel"   & semint  == "unint" & n2num == "plur")
relat.unint.sing <- subset(data.subj, related == "rel"   & semint  == "unint" & n2num == "sing")
unrel.int.plur   <- subset(data.subj, related == "unrel" & semint  == "integ" & n2num == "plur")
unrel.int.sing   <- subset(data.subj, related == "unrel" & semint  == "integ" & n2num == "sing")
unrel.unint.plur <- subset(data.subj, related == "unrel" & semint  == "unint" & n2num == "plur")
unrel.unint.sing <- subset(data.subj, related == "unrel" & semint  == "unint" & n2num == "sing")
relat.plur       <- subset(data.subj, related == "rel"   & n2num   == "plur")
relat.sing       <- subset(data.subj, related == "rel"   & n2num   == "sing")
unrel.plur       <- subset(data.subj, related == "unrel" & n2num   == "plur")
unrel.sing       <- subset(data.subj, related == "unrel" & n2num   == "sing")
integ.plur       <- subset(data.subj, semint  == "integ" & n2num   == "plur")
integ.sing       <- subset(data.subj, semint  == "integ" & n2num   == "sing")
unint.plur       <- subset(data.subj, semint  == "unint" & n2num   == "plur")
unint.sing       <- subset(data.subj, semint  == "unint" & n2num   == "sing")
integ.relat      <- subset(data.subj, semint  == "integ" & related == "rel")
integ.unrel      <- subset(data.subj, semint  == "integ" & related == "unrel")
unint.relat      <- subset(data.subj, semint  == "unint" & related == "rel")
unint.unrel      <- subset(data.subj, semint  == "unint" & related == "unrel")
# ------------------------- ARCSINE TRANSFORMED ERRORS WITH DYSFLUENCIES ----------------

arc <- f1errout 
arc$subj <- as.factor(arc$subj) 
arc$pct <- ifelse(arc$errd == 0 & arc$errcord == 0, 0, (arc$errd / (arc$errcord)) * 100)
arc$arcs <- 2*asin(sqrt(arc$pct/100))
arc.data.subj <- aggregate(arc$arcs, list(arc$subj, arc$semint, arc$related, arc$n2num ), mean)
colnames(arc.data.subj) <- c("subj", "semint", "related", "n2num", "arcerr") 
arc.integ <- subset(arc.data.subj, semint   ==  "integ")
arc.unint <- subset(arc.data.subj, semint   ==  "unint")
arc.relat <- subset(arc.data.subj, related  ==  "rel")
arc.unrel <- subset(arc.data.subj, related  ==  "unrel")
arc.sing  <- subset(arc.data.subj, n2num    ==  "sing")
arc.plur  <- subset(arc.data.subj, n2num    ==  "plur")
arc.relat.int.plur   <- subset(arc.data.subj, related == "rel"   & semint  == "integ" & n2num == "plur")
arc.relat.int.sing   <- subset(arc.data.subj, related == "rel"   & semint  == "integ" & n2num == "sing")
arc.relat.unint.plur <- subset(arc.data.subj, related == "rel"   & semint  == "unint" & n2num == "plur")
arc.relat.unint.sing <- subset(arc.data.subj, related == "rel"   & semint  == "unint" & n2num == "sing")
arc.unrel.int.plur   <- subset(arc.data.subj, related == "unrel" & semint  == "integ" & n2num == "plur")
arc.unrel.int.sing   <- subset(arc.data.subj, related == "unrel" & semint  == "integ" & n2num == "sing")
arc.unrel.unint.plur <- subset(arc.data.subj, related == "unrel" & semint  == "unint" & n2num == "plur")
arc.unrel.unint.sing <- subset(arc.data.subj, related == "unrel" & semint  == "unint" & n2num == "sing")
arc.relat.plur       <- subset(arc.data.subj, related == "rel"   & n2num   == "plur")
arc.relat.sing       <- subset(arc.data.subj, related == "rel"   & n2num   == "sing")
arc.unrel.plur       <- subset(arc.data.subj, related == "unrel" & n2num   == "plur")
arc.unrel.sing       <- subset(arc.data.subj, related == "unrel" & n2num   == "sing")
arc.integ.plur       <- subset(arc.data.subj, semint  == "integ" & n2num   == "plur")
arc.integ.sing       <- subset(arc.data.subj, semint  == "integ" & n2num   == "sing")
arc.unint.plur       <- subset(arc.data.subj, semint  == "unint" & n2num   == "plur")
arc.unint.sing       <- subset(arc.data.subj, semint  == "unint" & n2num   == "sing")
arc.integ.relat      <- subset(arc.data.subj, semint  == "integ" & related == "rel")
arc.integ.unrel      <- subset(arc.data.subj, semint  == "integ" & related == "unrel")
arc.unint.relat      <- subset(arc.data.subj, semint  == "unint" & related == "rel")
arc.unint.unrel      <- subset(arc.data.subj, semint  == "unint" & related == "unrel")
# ------------------------- ERRORS WITH NO DYSFLUENCIES ----------------

nodys <- f1errout 
nodys$subj <- as.factor(nodys$subj) 
nodys$pct <- ifelse(nodys$errnd == 0 & nodys$errcornd == 0, 0, (nodys$errnd / (nodys$errcornd)) * 100)
nodys.data.subj <- aggregate(nodys$pct, list(nodys$subj, nodys$semint, nodys$related, nodys$n2num ), mean)
colnames(nodys.data.subj) <- c("subj", "semint", "related", "n2num", "nodys") 
nodys.integ <- subset(nodys.data.subj, semint   ==  "integ")
nodys.unint <- subset(nodys.data.subj, semint   ==  "unint")
nodys.relat <- subset(nodys.data.subj, related  ==  "rel")
nodys.unrel <- subset(nodys.data.subj, related  ==  "unrel")
nodys.sing  <- subset(nodys.data.subj, n2num    ==  "sing")
nodys.plur  <- subset(nodys.data.subj, n2num    ==  "plur")
nodys.relat.int.plur   <- subset(nodys.data.subj, related == "rel"   & semint  == "integ" & n2num == "plur")
nodys.relat.int.sing   <- subset(nodys.data.subj, related == "rel"   & semint  == "integ" & n2num == "sing")
nodys.relat.unint.plur <- subset(nodys.data.subj, related == "rel"   & semint  == "unint" & n2num == "plur")
nodys.relat.unint.sing <- subset(nodys.data.subj, related == "rel"   & semint  == "unint" & n2num == "sing")
nodys.unrel.int.plur   <- subset(nodys.data.subj, related == "unrel" & semint  == "integ" & n2num == "plur")
nodys.unrel.int.sing   <- subset(nodys.data.subj, related == "unrel" & semint  == "integ" & n2num == "sing")
nodys.unrel.unint.plur <- subset(nodys.data.subj, related == "unrel" & semint  == "unint" & n2num == "plur")
nodys.unrel.unint.sing <- subset(nodys.data.subj, related == "unrel" & semint  == "unint" & n2num == "sing")
nodys.relat.plur       <- subset(nodys.data.subj, related == "rel"   & n2num   == "plur")
nodys.relat.sing       <- subset(nodys.data.subj, related == "rel"   & n2num   == "sing")
nodys.unrel.plur       <- subset(nodys.data.subj, related == "unrel" & n2num   == "plur")
nodys.unrel.sing       <- subset(nodys.data.subj, related == "unrel" & n2num   == "sing")
nodys.integ.plur       <- subset(nodys.data.subj, semint  == "integ" & n2num   == "plur")
nodys.integ.sing       <- subset(nodys.data.subj, semint  == "integ" & n2num   == "sing")
nodys.unint.plur       <- subset(nodys.data.subj, semint  == "unint" & n2num   == "plur")
nodys.unint.sing       <- subset(nodys.data.subj, semint  == "unint" & n2num   == "sing")
nodys.integ.relat      <- subset(nodys.data.subj, semint  == "integ" & related == "rel")
nodys.integ.unrel      <- subset(nodys.data.subj, semint  == "integ" & related == "unrel")
nodys.unint.relat      <- subset(nodys.data.subj, semint  == "unint" & related == "rel")
nodys.unint.unrel      <- subset(nodys.data.subj, semint  == "unint" & related == "unrel")
# ------------------------  ERRORS COUNTS ----------------


cnt <- f1errout 
cnt$subj <- as.factor(cnt$subj) 
cnt.data.subj <- aggregate(cnt$errd, list(cnt$subj, cnt$semint, cnt$related, cnt$n2num ), sum)
colnames(cnt.data.subj) <- c("subj", "semint", "related", "n2num", "count") 
cnt.integ <- subset(cnt.data.subj, semint   ==  "integ")
cnt.unint <- subset(cnt.data.subj, semint   ==  "unint")
cnt.relat <- subset(cnt.data.subj, related  ==  "rel")
cnt.unrel <- subset(cnt.data.subj, related  ==  "unrel")
cnt.sing  <- subset(cnt.data.subj, n2num    ==  "sing")
cnt.plur  <- subset(cnt.data.subj, n2num    ==  "plur")
cnt.relat.int.plur   <- subset(cnt.data.subj, related == "rel"   & semint  == "integ" & n2num == "plur")
cnt.relat.int.sing   <- subset(cnt.data.subj, related == "rel"   & semint  == "integ" & n2num == "sing")
cnt.relat.unint.plur <- subset(cnt.data.subj, related == "rel"   & semint  == "unint" & n2num == "plur")
cnt.relat.unint.sing <- subset(cnt.data.subj, related == "rel"   & semint  == "unint" & n2num == "sing")
cnt.unrel.int.plur   <- subset(cnt.data.subj, related == "unrel" & semint  == "integ" & n2num == "plur")
cnt.unrel.int.sing   <- subset(cnt.data.subj, related == "unrel" & semint  == "integ" & n2num == "sing")
cnt.unrel.unint.plur <- subset(cnt.data.subj, related == "unrel" & semint  == "unint" & n2num == "plur")
cnt.unrel.unint.sing <- subset(cnt.data.subj, related == "unrel" & semint  == "unint" & n2num == "sing")
cnt.relat.plur       <- subset(cnt.data.subj, related == "rel"   & n2num   == "plur")
cnt.relat.sing       <- subset(cnt.data.subj, related == "rel"   & n2num   == "sing")
cnt.unrel.plur       <- subset(cnt.data.subj, related == "unrel" & n2num   == "plur")
cnt.unrel.sing       <- subset(cnt.data.subj, related == "unrel" & n2num   == "sing")
cnt.integ.plur       <- subset(cnt.data.subj, semint  == "integ" & n2num   == "plur")
cnt.integ.sing       <- subset(cnt.data.subj, semint  == "integ" & n2num   == "sing")
cnt.unint.plur       <- subset(cnt.data.subj, semint  == "unint" & n2num   == "plur")
cnt.unint.sing       <- subset(cnt.data.subj, semint  == "unint" & n2num   == "sing")
cnt.integ.relat      <- subset(cnt.data.subj, semint  == "integ" & related == "rel")
cnt.integ.unrel      <- subset(cnt.data.subj, semint  == "integ" & related == "unrel")
cnt.unint.relat      <- subset(cnt.data.subj, semint  == "unint" & related == "rel")
cnt.unint.unrel      <- subset(cnt.data.subj, semint  == "unint" & related == "unrel")

