
# # ====================================================================================================
# # --------------------------------------PROPERTY ITEMS ANALYSES---------------------
# # ====================================================================================================

f1errout <- read.table("data/SR2_F1_errprop.txt", header = T)
d <- f1errout
d$subj <- as.factor(d$subj)
d$pct <- ifelse(d$errd == 0 & d$errcord == 0, 0, (d$errd / (d$errcord)) * 100)
data.subj <- aggregate(d$pct, list(d$subj, d$related, d$n2num ), mean)
colnames(data.subj) <- c("subj", "related", "n2num", "error")
relat            <- subset(data.subj, related == "rel")
assoc            <- subset(data.subj, related == "assoc")
unrel            <- subset(data.subj, related == "unrel")
sing             <- subset(data.subj, n2num   == "sing")
plur             <- subset(data.subj, n2num   == "plur")
relat.plur       <- subset(data.subj, related == "rel"   & n2num   == "plur")
relat.sing       <- subset(data.subj, related == "rel"   & n2num   == "sing")
assoc.plur       <- subset(data.subj, related == "assoc" & n2num   == "plur")
assoc.sing       <- subset(data.subj, related == "assoc" & n2num   == "sing")
unrel.plur       <- subset(data.subj, related == "unrel" & n2num   == "plur")
unrel.sing       <- subset(data.subj, related == "unrel" & n2num   == "sing")
relat.assoc      <- subset(data.subj, related     != "unrel")
relat.assoc.plur <- subset(data.subj, related     != "unrel" & n2num == "plur")
relat.assoc.sing <- subset(data.subj, related     != "unrel" & n2num == "sing")
relat.unrel      <- subset(data.subj, related     != "assoc")
relat.unrel.plur <- subset(data.subj, related     != "assoc" & n2num == "plur")
relat.unrel.sing <- subset(data.subj, related     != "assoc" & n2num == "sing")
assoc.unrel      <- subset(data.subj, related     != "rel")
assoc.unrel.plur <- subset(data.subj, related     != "rel" & n2num == "plur")
assoc.unrel.sing <- subset(data.subj, related     != "rel" & n2num == "sing")
relat.plur       <- subset(data.subj, related     == "rel"   & n2num   == "plur")
relat.sing       <- subset(data.subj, related     == "rel"   & n2num   == "sing")
assoc.plur       <- subset(data.subj, related     == "assoc" & n2num   == "plur")
assoc.sing       <- subset(data.subj, related     == "assoc" & n2num   == "sing")
unrel.plur       <- subset(data.subj, related     == "unrel" & n2num   == "plur")
unrel.sing       <- subset(data.subj, related     == "unrel" & n2num   == "sing")
# ------------------------- ARCSINE TRANSFORMED ERRORS WITH DYSFLUENCIES ----------------

arc <- f1errout 
arc$subj <- as.factor(arc$subj) 
arc$pct <- ifelse(arc$errd == 0 & arc$errcord == 0, 0, (arc$errd / (arc$errcord)) * 100)
arc$arcs <- 2*asin(sqrt(arc$pct/100))
arc.data.subj <- aggregate(arc$arcs, list(arc$subj, arc$semint, arc$related, arc$n2num ), mean)
colnames(arc.data.subj) <- c("subj", "semint", "related", "n2num", "arcerr") 
arc.relat            <- subset(arc.data.subj, related == "rel")
arc.assoc            <- subset(arc.data.subj, related == "assoc")
arc.unrel            <- subset(arc.data.subj, related == "unrel")
arc.sing             <- subset(arc.data.subj, n2num   == "sing")
arc.plur             <- subset(arc.data.subj, n2num   == "plur")
arc.relat.plur       <- subset(arc.data.subj, related == "rel"   & n2num   == "plur")
arc.relat.sing       <- subset(arc.data.subj, related == "rel"   & n2num   == "sing")
arc.assoc.plur       <- subset(arc.data.subj, related == "assoc" & n2num   == "plur")
arc.assoc.sing       <- subset(arc.data.subj, related == "assoc" & n2num   == "sing")
arc.unrel.plur       <- subset(arc.data.subj, related == "unrel" & n2num   == "plur")
arc.unrel.sing       <- subset(arc.data.subj, related == "unrel" & n2num   == "sing")
arc.relat.assoc      <- subset(arc.data.subj, related     != "unrel")
arc.relat.assoc.plur <- subset(arc.data.subj, related     != "unrel" & n2num == "plur")
arc.relat.assoc.sing <- subset(arc.data.subj, related     != "unrel" & n2num == "sing")
arc.relat.unrel      <- subset(arc.data.subj, related     != "assoc")
arc.relat.unrel.plur <- subset(arc.data.subj, related     != "assoc" & n2num == "plur")
arc.relat.unrel.sing <- subset(arc.data.subj, related     != "assoc" & n2num == "sing")
arc.assoc.unrel      <- subset(arc.data.subj, related     != "rel")
arc.assoc.unrel.plur <- subset(arc.data.subj, related     != "rel" & n2num == "plur")
arc.assoc.unrel.sing <- subset(arc.data.subj, related     != "rel" & n2num == "sing")
arc.relat.plur       <- subset(arc.data.subj, related     == "rel"   & n2num   == "plur")
arc.relat.sing       <- subset(arc.data.subj, related     == "rel"   & n2num   == "sing")
arc.assoc.plur       <- subset(arc.data.subj, related     == "assoc" & n2num   == "plur")
arc.assoc.sing       <- subset(arc.data.subj, related     == "assoc" & n2num   == "sing")
arc.unrel.plur       <- subset(arc.data.subj, related     == "unrel" & n2num   == "plur")
arc.unrel.sing       <- subset(arc.data.subj, related     == "unrel" & n2num   == "sing")
# ------------------------- ERRORS WITH NO DYSFLUENCIES ----------------

nodys <- f1errout 
nodys$subj <- as.factor(nodys$subj) 
nodys$pct <- ifelse(nodys$errnd == 0 & nodys$errcornd == 0, 0, (nodys$errnd / (nodys$errcornd)) * 100)
nodys.data.subj <- aggregate(nodys$pct, list(nodys$subj, nodys$semint, nodys$related, nodys$n2num ), mean)
colnames(nodys.data.subj) <- c("subj", "semint", "related", "n2num", "nodys") 
nodys.relat            <- subset(nodys.data.subj, related == "rel")
nodys.assoc            <- subset(nodys.data.subj, related == "assoc")
nodys.unrel            <- subset(nodys.data.subj, related == "unrel")
nodys.sing             <- subset(nodys.data.subj, n2num   == "sing")
nodys.plur             <- subset(nodys.data.subj, n2num   == "plur")
nodys.relat.plur       <- subset(nodys.data.subj, related == "rel"   & n2num   == "plur")
nodys.relat.sing       <- subset(nodys.data.subj, related == "rel"   & n2num   == "sing")
nodys.assoc.plur       <- subset(nodys.data.subj, related == "assoc" & n2num   == "plur")
nodys.assoc.sing       <- subset(nodys.data.subj, related == "assoc" & n2num   == "sing")
nodys.unrel.plur       <- subset(nodys.data.subj, related == "unrel" & n2num   == "plur")
nodys.unrel.sing       <- subset(nodys.data.subj, related == "unrel" & n2num   == "sing")
nodys.relat.assoc      <- subset(nodys.data.subj, related     != "unrel")
nodys.relat.assoc.plur <- subset(nodys.data.subj, related     != "unrel" & n2num == "plur")
nodys.relat.assoc.sing <- subset(nodys.data.subj, related     != "unrel" & n2num == "sing")
nodys.relat.unrel      <- subset(nodys.data.subj, related     != "assoc")
nodys.relat.unrel.plur <- subset(nodys.data.subj, related     != "assoc" & n2num == "plur")
nodys.relat.unrel.sing <- subset(nodys.data.subj, related     != "assoc" & n2num == "sing")
nodys.assoc.unrel      <- subset(nodys.data.subj, related     != "rel")
nodys.assoc.unrel.plur <- subset(nodys.data.subj, related     != "rel" & n2num == "plur")
nodys.assoc.unrel.sing <- subset(nodys.data.subj, related     != "rel" & n2num == "sing")
nodys.relat.plur       <- subset(nodys.data.subj, related     == "rel"   & n2num   == "plur")
nodys.relat.sing       <- subset(nodys.data.subj, related     == "rel"   & n2num   == "sing")
nodys.assoc.plur       <- subset(nodys.data.subj, related     == "assoc" & n2num   == "plur")
nodys.assoc.sing       <- subset(nodys.data.subj, related     == "assoc" & n2num   == "sing")
nodys.unrel.plur       <- subset(nodys.data.subj, related     == "unrel" & n2num   == "plur")
nodys.unrel.sing       <- subset(nodys.data.subj, related     == "unrel" & n2num   == "sing")
# ------------------------  ERRORS COUNTS ----------------


cnt <- f1errout 
cnt$subj <- as.factor(cnt$subj) 
cnt.data.subj <- aggregate(cnt$errd, list(cnt$subj, cnt$semint, cnt$related, cnt$n2num ), sum)
colnames(cnt.data.subj) <- c("subj", "semint", "related", "n2num", "count") 
cnt.relat            <- subset(cnt.data.subj, related == "rel")
cnt.assoc            <- subset(cnt.data.subj, related == "assoc")
cnt.unrel            <- subset(cnt.data.subj, related == "unrel")
cnt.sing             <- subset(cnt.data.subj, n2num   == "sing")
cnt.plur             <- subset(cnt.data.subj, n2num   == "plur")
cnt.relat.plur       <- subset(cnt.data.subj, related == "rel"   & n2num   == "plur")
cnt.relat.sing       <- subset(cnt.data.subj, related == "rel"   & n2num   == "sing")
cnt.assoc.plur       <- subset(cnt.data.subj, related == "assoc" & n2num   == "plur")
cnt.assoc.sing       <- subset(cnt.data.subj, related == "assoc" & n2num   == "sing")
cnt.unrel.plur       <- subset(cnt.data.subj, related == "unrel" & n2num   == "plur")
cnt.unrel.sing       <- subset(cnt.data.subj, related == "unrel" & n2num   == "sing")
cnt.relat.assoc      <- subset(cnt.data.subj, related     != "unrel")
cnt.relat.assoc.plur <- subset(cnt.data.subj, related     != "unrel" & n2num == "plur")
cnt.relat.assoc.sing <- subset(cnt.data.subj, related     != "unrel" & n2num == "sing")
cnt.relat.unrel      <- subset(cnt.data.subj, related     != "assoc")
cnt.relat.unrel.plur <- subset(cnt.data.subj, related     != "assoc" & n2num == "plur")
cnt.relat.unrel.sing <- subset(cnt.data.subj, related     != "assoc" & n2num == "sing")
cnt.assoc.unrel      <- subset(cnt.data.subj, related     != "rel")
cnt.assoc.unrel.plur <- subset(cnt.data.subj, related     != "rel" & n2num == "plur")
cnt.assoc.unrel.sing <- subset(cnt.data.subj, related     != "rel" & n2num == "sing")
cnt.relat.plur       <- subset(cnt.data.subj, related     == "rel"   & n2num   == "plur")
cnt.relat.sing       <- subset(cnt.data.subj, related     == "rel"   & n2num   == "sing")
cnt.assoc.plur       <- subset(cnt.data.subj, related     == "assoc" & n2num   == "plur")
cnt.assoc.sing       <- subset(cnt.data.subj, related     == "assoc" & n2num   == "sing")
cnt.unrel.plur       <- subset(cnt.data.subj, related     == "unrel" & n2num   == "plur")
cnt.unrel.sing       <- subset(cnt.data.subj, related     == "unrel" & n2num   == "sing")