
d.base           <- read.csv("data/SR1&2_coding.csv")
d.sr            <- subset(d.base, subexpt == "SemRel")
d.sr            <- subset(d.sr, subject != 50)
d.sr            <- subset(d.sr, subject != 112)
d.sr            <- subset(d.sr, subject != 121)
d.sr            <- subset(d.sr, subject != 138)
d.sr            <- subset(d.sr, subject != 157)
d.sr            <- subset(d.sr, subject != 158)
d.sr            <- subset(d.sr, subject != 191)
d.sr            <- subset(d.sr, subject != 192)
d.sr            <- subset(d.sr, subject != 219)

d.sr$errcord <- (d.sr$errd + d.sr$corrd)

d.sr$integrated <- as.factor(d.sr$integ)
d.sr$related    <- as.factor(d.sr$related)
d.sr$related    <- droplevels(d.sr$rel)
d.sr$n2num      <- as.factor(d.sr$n2num)
d.sr$item       <- as.factor(d.sr$item)
d.sr$subject    <- as.factor(d.sr$subject)
# -------------------- SEMREL: ADDITIONAL SUBSETTING -----------------
integ <- subset(d.sr, integrated   ==  "integ")
unint <- subset(d.sr, integrated   ==  "unint")
relat <- subset(d.sr, related  ==  "rel")
unrel <- subset(d.sr, related  ==  "unrel")
sing  <- subset(d.sr, n2num    ==  "sing")
plur  <- subset(d.sr, n2num    ==  "plur")

#Below, additional subsetted groups
relat.int.plur   <- subset(d.sr, related     == "rel"   & integrated == "integ" & n2num == "plur")
relat.int.sing   <- subset(d.sr, related     == "rel"   & integrated == "integ" & n2num == "sing")
relat.unint.plur <- subset(d.sr, related     == "rel"   & integrated == "unint" & n2num == "plur")
relat.unint.sing <- subset(d.sr, related     == "rel"   & integrated == "unint" & n2num == "sing")
unrel.int.plur   <- subset(d.sr, related     == "unrel" & integrated == "integ" & n2num == "plur")
unrel.int.sing   <- subset(d.sr, related     == "unrel" & integrated == "integ" & n2num == "sing")
unrel.unint.plur <- subset(d.sr, related     == "unrel" & integrated == "unint" & n2num == "plur")
unrel.unint.sing <- subset(d.sr, related     == "unrel" & integrated == "unint" & n2num == "sing")
relat.plur       <- subset(d.sr, related     == "rel"   & n2num      == "plur")
relat.sing       <- subset(d.sr, related     == "rel"   & n2num      == "sing")
unrel.plur       <- subset(d.sr, related     == "unrel" & n2num      == "plur")
unrel.sing       <- subset(d.sr, related     == "unrel" & n2num      == "sing")
integ.plur       <- subset(d.sr, integrated  == "integ" & n2num      == "plur")
integ.sing       <- subset(d.sr, integrated  == "integ" & n2num      == "sing")
unint.plur       <- subset(d.sr, integrated  == "unint" & n2num      == "plur")
unint.sing       <- subset(d.sr, integrated  == "unint" & n2num      == "sing")
integ.relat      <- subset(d.sr, integrated  == "integ" & related    == "rel")
integ.unrel      <- subset(d.sr, integrated  == "integ" & related    == "unrel")
unint.relat      <- subset(d.sr, integrated  == "unint" & related    == "rel")
unint.unrel      <- subset(d.sr, integrated  == "unint" & related    == "unrel")


